import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import api from '../api/api';
import { Award, ArrowLeft, CheckCircle2, XCircle, ChevronRight, AlertCircle, RefreshCw } from 'lucide-react';

export default function QuizPage() {
  const { quizId } = useParams();
  const [questions, setQuestions] = useState([]);
  const [attempts, setAttempts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeStep, setActiveStep] = useState('INFO'); // INFO, ATTEMPT, RESULT

  // Attempt states
  const [currentIdx, setCurrentIdx] = useState(0);
  const [answers, setAnswers] = useState({});
  const [submitting, setSubmitting] = useState(false);
  const [result, setResult] = useState(null);

  const navigate = useNavigate();

  useEffect(() => {
    fetchQuizQuestionsAndAttempts();
  }, [quizId]);

  const fetchQuizQuestionsAndAttempts = async () => {
    try {
      const questionsRes = await api.get(`/quizzes/${quizId}/questions`);
      setQuestions(questionsRes.data);

      const attemptsRes = await api.get(`/quizzes/${quizId}/attempts`);
      setAttempts(attemptsRes.data);
    } catch (e) {
      console.error(e);
      alert('Access Denied: You must be enrolled in this course to take the quiz.');
      navigate('/dashboard');
    } finally {
      setLoading(false);
    }
  };

  const startQuiz = () => {
    setAnswers({});
    setCurrentIdx(0);
    setActiveStep('ATTEMPT');
  };

  const selectOption = (questionId, option) => {
    setAnswers({
      ...answers,
      [questionId]: option
    });
  };

  const nextQuestion = () => {
    if (currentIdx < questions.length - 1) {
      setCurrentIdx(currentIdx + 1);
    }
  };

  const prevQuestion = () => {
    if (currentIdx > 0) {
      setCurrentIdx(currentIdx - 1);
    }
  };

  const submitQuiz = async () => {
    setSubmitting(true);
    try {
      const response = await api.post(`/quizzes/${quizId}/attempt`, {
        answers: answers
      });
      setResult(response.data);
      setActiveStep('RESULT');

      // Reload attempts list
      const attemptsRes = await api.get(`/quizzes/${quizId}/attempts`);
      setAttempts(attemptsRes.data);
    } catch (e) {
      console.error(e);
      alert('Failed to submit quiz attempt.');
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '80vh' }}>
        <div className="spinner"></div>
      </div>
    );
  }

  const currentQ = questions[currentIdx];

  return (
    <div style={{ padding: '60px 0', minHeight: '100vh' }}>
      <div className="container" style={{ maxWidth: '720px' }}>
        
        {/* Step 1: Info & Attempts History */}
        {activeStep === 'INFO' && (
          <div className="glass-card" style={{ padding: '40px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '24px' }}>
              <Award size={36} color="var(--primary)" />
              <h1 style={{ fontSize: '2rem' }}>AI MCQ Quiz Assessment</h1>
            </div>

            <p style={{ color: 'var(--text-secondary)', lineHeight: 1.6, marginBottom: '32px' }}>
              This quiz consists of 5 multiple-choice questions generated by our AI engine from the course notes.
              Test your understanding to unlock skills on your profile!
            </p>

            <button onClick={startQuiz} className="btn btn-primary" style={{ width: '100%', padding: '14px', marginBottom: '40px' }}>
              Start Assessment
            </button>

            <h3 style={{ fontSize: '1.25rem', marginBottom: '16px' }}>Your Previous Attempts</h3>
            {attempts.length === 0 ? (
              <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>You haven't attempted this quiz yet.</p>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                {attempts.map((attempt) => {
                  const percent = Math.round((attempt.score * 100) / attempt.totalQuestions);
                  return (
                    <div key={attempt.id} style={{
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                      background: 'rgba(255,255,255,0.02)',
                      border: '1px solid var(--border-color)',
                      padding: '16px 20px',
                      borderRadius: '8px'
                    }}>
                      <div>
                        <div style={{ fontWeight: 600, color: '#fff' }}>Score: {attempt.score} / {attempt.totalQuestions}</div>
                        <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                          Attempted on {new Date(attempt.attemptedAt).toLocaleString()}
                        </span>
                      </div>
                      <span className="badge badge-success" style={{
                        background: percent >= 70 ? 'rgba(16,185,129,0.15)' : 'rgba(245,158,11,0.15)',
                        color: percent >= 70 ? 'var(--secondary)' : 'var(--warning)'
                      }}>
                        {percent}%
                      </span>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        )}

        {/* Step 2: Answering questions */}
        {activeStep === 'ATTEMPT' && currentQ && (
          <div className="glass-card" style={{ padding: '40px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '32px' }}>
              <span style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
                Question {currentIdx + 1} of {questions.length}
              </span>
              <div style={{ width: '120px', height: '6px', background: 'rgba(255,255,255,0.1)', borderRadius: '3px' }}>
                <div style={{
                  width: `${((currentIdx + 1) * 100) / questions.length}%`,
                  height: '100%',
                  background: 'var(--primary)',
                  borderRadius: '3px'
                }}></div>
              </div>
            </div>

            <h2 style={{ fontSize: '1.4rem', marginBottom: '24px', lineHeight: 1.5 }}>{currentQ.question}</h2>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px', marginBottom: '40px' }}>
              {['A', 'B', 'C', 'D'].map((opt) => {
                const optText = currentQ[`option${opt}`];
                const isSelected = answers[currentQ.id] === opt;
                return (
                  <button
                    key={opt}
                    onClick={() => selectOption(currentQ.id, opt)}
                    style={{
                      background: isSelected ? 'rgba(99, 102, 241, 0.15)' : 'rgba(255,255,255,0.02)',
                      border: `1px solid ${isSelected ? 'var(--primary)' : 'var(--border-color)'}`,
                      color: isSelected ? '#fff' : 'var(--text-secondary)',
                      padding: '16px 20px',
                      borderRadius: '8px',
                      textAlign: 'left',
                      cursor: 'pointer',
                      fontSize: '0.95rem',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '12px',
                      transition: 'all 0.15s ease'
                    }}
                  >
                    <span style={{
                      display: 'inline-flex',
                      width: '28px',
                      height: '28px',
                      borderRadius: '50%',
                      background: isSelected ? 'var(--primary)' : 'rgba(255,255,255,0.05)',
                      color: isSelected ? '#fff' : 'var(--text-secondary)',
                      alignItems: 'center',
                      justifyContent: 'center',
                      fontWeight: 700
                    }}>{opt}</span>
                    <span>{optText}</span>
                  </button>
                );
              })}
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <button
                onClick={prevQuestion}
                disabled={currentIdx === 0}
                className="btn btn-outline"
                style={{ opacity: currentIdx === 0 ? 0.5 : 1 }}
              >
                Previous
              </button>
              {currentIdx === questions.length - 1 ? (
                <button
                  onClick={submitQuiz}
                  disabled={submitting}
                  className="btn btn-secondary"
                >
                  {submitting ? 'Submitting...' : 'Submit Assessment'}
                </button>
              ) : (
                <button onClick={nextQuestion} className="btn btn-primary">
                  Next
                </button>
              )}
            </div>
          </div>
        )}

        {/* Step 3: Result Feedback & AI Explanations */}
        {activeStep === 'RESULT' && result && (
          <div className="glass-card" style={{ padding: '40px' }}>
            <div style={{ textAlign: 'center', marginBottom: '40px' }}>
              <Award size={48} color="var(--secondary)" style={{ margin: '0 auto 16px' }} />
              <h1 style={{ fontSize: '2.2rem' }}>Assessment Completed</h1>
              <p style={{ color: 'var(--text-secondary)', marginTop: '8px' }}>Your responses have been processed.</p>
              
              <div style={{
                display: 'inline-flex',
                background: 'rgba(255,255,255,0.03)',
                border: '1px solid var(--border-color)',
                padding: '24px 40px',
                borderRadius: '16px',
                marginTop: '24px',
                flexDirection: 'column',
                gap: '8px'
              }}>
                <span style={{ fontSize: '3rem', fontWeight: 800, color: 'var(--secondary)' }}>
                  {result.score} / {result.totalQuestions}
                </span>
                <span style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
                  Percentage: {Math.round((result.score * 100) / result.totalQuestions)}%
                </span>
              </div>
            </div>

            <h3 style={{ fontSize: '1.25rem', marginBottom: '20px', borderBottom: '1px solid var(--border-color)', paddingBottom: '12px' }}>Review Questions</h3>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: '32px', marginBottom: '40px' }}>
              {questions.map((q, idx) => {
                const selectedOpt = answers[q.id];
                const correctOpt = q.correctAnswer;
                const isCorrect = selectedOpt === correctOpt;
                
                return (
                  <div key={q.id}>
                    <div style={{ display: 'flex', gap: '8px', alignItems: 'flex-start', marginBottom: '12px' }}>
                      {isCorrect ? (
                        <CheckCircle2 color="var(--secondary)" style={{ flexShrink: 0, marginTop: '2px' }} />
                      ) : (
                        <XCircle color="var(--danger)" style={{ flexShrink: 0, marginTop: '2px' }} />
                      )}
                      <h4 style={{ fontSize: '1.05rem', lineHeight: 1.4, color: '#fff' }}>
                        {idx + 1}. {q.question}
                      </h4>
                    </div>

                    <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', paddingLeft: '32px' }}>
                      {['A', 'B', 'C', 'D'].map((opt) => (
                        <div key={opt} style={{
                          padding: '10px 14px',
                          borderRadius: '6px',
                          fontSize: '0.9rem',
                          background: opt === correctOpt 
                            ? 'rgba(16, 185, 129, 0.1)' 
                            : (opt === selectedOpt ? 'rgba(239, 68, 68, 0.1)' : 'rgba(255,255,255,0.01)'),
                          border: `1px solid ${opt === correctOpt 
                            ? 'rgba(16, 185, 129, 0.2)' 
                            : (opt === selectedOpt ? 'rgba(239, 68, 68, 0.2)' : 'var(--border-color)')}`,
                          color: opt === correctOpt ? 'var(--secondary)' : (opt === selectedOpt ? 'var(--danger)' : 'var(--text-secondary)')
                        }}>
                          {opt}. {q[`option${opt}`]}
                        </div>
                      ))}
                    </div>

                    {/* AI Explanation Box */}
                    <div style={{
                      marginTop: '16px',
                      marginLeft: '32px',
                      background: 'rgba(99, 102, 241, 0.05)',
                      border: '1px solid rgba(99, 102, 241, 0.15)',
                      padding: '16px',
                      borderRadius: '8px',
                      fontSize: '0.85rem',
                      display: 'flex',
                      gap: '8px',
                      alignItems: 'flex-start'
                    }}>
                      <AlertCircle size={16} color="var(--primary)" style={{ flexShrink: 0, marginTop: '2px' }} />
                      <div>
                        <strong style={{ color: '#fff', display: 'block', marginBottom: '4px' }}>AI Explanation:</strong>
                        <span style={{ color: 'var(--text-secondary)' }}>{q.explanation}</span>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>

            <div style={{ display: 'flex', gap: '16px' }}>
              <button onClick={startQuiz} className="btn btn-outline" style={{ flex: 1 }}>
                <RefreshCw size={16} /> Retake Assessment
              </button>
              <button onClick={() => navigate(-1)} className="btn btn-primary" style={{ flex: 1 }}>
                Back to Course
              </button>
            </div>
          </div>
        )}

      </div>
    </div>
  );
}
