import { requireAuth } from './auth.js';
import { apiFetch } from './api.js';

let quizId = null;
let questions = [];
let attempts = [];
let activeStep = 'INFO'; // INFO, ATTEMPT, RESULT

let currentIdx = 0;
let answers = {};
let submitting = false;
let result = null;

document.addEventListener('DOMContentLoaded', async () => {
  const user = requireAuth('STUDENT');
  if (!user) return;

  const urlParams = new URLSearchParams(window.location.search);
  quizId = urlParams.get('quizId');

  if (!quizId) {
    window.location.href = 'dashboard.html';
    return;
  }

  fetchQuizData();
});

async function fetchQuizData() {
  const container = document.getElementById('quiz-container');
  if (!container) return;

  try {
    questions = await apiFetch(`/quizzes/${quizId}/questions`);
    attempts = await apiFetch(`/quizzes/${quizId}/attempts`);
    renderQuizView();
  } catch (err) {
    console.error(err);
    alert('Access Denied: You must be enrolled in this course to take the quiz.');
    window.location.href = 'dashboard.html';
  }
}

function renderQuizView() {
  const container = document.getElementById('quiz-container');
  if (!container) return;

  if (activeStep === 'INFO') {
    container.innerHTML = `
      <div class="glass-card" style="padding: 40px;">
        <div style="display: flex; align-items: center; gap: 12px; margin-bottom: 24px;">
          <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="8" r="7"></circle>
            <polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"></polyline>
          </svg>
          <h1 style="font-size: 2rem;">AI MCQ Quiz Assessment</h1>
        </div>

        <p style="color: var(--text-secondary); line-height: 1.6; margin-bottom: 32px;">
          This quiz consists of ${questions.length} multiple-choice questions generated by our AI engine from the course notes.
          Test your understanding to unlock skills on your profile!
        </p>

        <button id="start-quiz-btn" class="btn btn-primary" style="width: 100%; padding: 14px; margin-bottom: 40px;">
          Start Assessment
        </button>

        <h3 style="font-size: 1.25rem; margin-bottom: 16px;">Your Previous Attempts</h3>
        ${attempts.length === 0 ? `
          <p style="color: var(--text-muted); font-size: 0.9rem;">You haven't attempted this quiz yet.</p>
        ` : `
          <div style="display: flex; flex-direction: column; gap: 12px;">
            ${attempts.map(attempt => {
              const percent = Math.round((attempt.score * 100) / attempt.totalQuestions);
              return `
                <div style="display: flex; justify-content: space-between; align-items: center; background: rgba(255,255,255,0.02); border: 1px solid var(--border-color); padding: 16px 20px; border-radius: 8px;">
                  <div>
                    <div style="font-weight: 600; color: #fff;">Score: ${attempt.score} / ${attempt.totalQuestions}</div>
                    <span style="font-size: 0.8rem; color: var(--text-muted);">
                      Attempted on ${new Date(attempt.attemptedAt).toLocaleString()}
                    </span>
                  </div>
                  <span class="badge" style="background: ${percent >= 70 ? 'rgba(16,185,129,0.15)' : 'rgba(245,158,11,0.15)'}; color: ${percent >= 70 ? 'var(--secondary)' : 'var(--warning)'};">
                    ${percent}%
                  </span>
                </div>
              `;
            }).join('')}
          </div>
        `}
      </div>
    `;

    const startBtn = document.getElementById('start-quiz-btn');
    if (startBtn) {
      startBtn.addEventListener('click', () => {
        answers = {};
        currentIdx = 0;
        activeStep = 'ATTEMPT';
        renderQuizView();
      });
    }

  } else if (activeStep === 'ATTEMPT') {
    const currentQ = questions[currentIdx];
    if (!currentQ) return;

    container.innerHTML = `
      <div class="glass-card" style="padding: 40px;">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 32px;">
          <span style="font-size: 0.9rem; color: var(--text-secondary);">
            Question ${currentIdx + 1} of ${questions.length}
          </span>
          <div style="width: 120px; height: 6px; background: rgba(255,255,255,0.1); border-radius: 3px;">
            <div style="width: ${((currentIdx + 1) * 100) / questions.length}%; height: 100%; background: var(--primary); border-radius: 3px;"></div>
          </div>
        </div>

        <h2 style="font-size: 1.4rem; margin-bottom: 24px; line-height: 1.5;">${currentQ.question}</h2>

        <div style="display: flex; flex-direction: column; gap: 16px; margin-bottom: 40px;">
          ${['A', 'B', 'C', 'D'].map(opt => {
            const optText = currentQ[`option${opt}`];
            const isSelected = answers[currentQ.id] === opt;
            return `
              <button
                type="button"
                class="option-btn"
                data-option="${opt}"
                style="background: ${isSelected ? 'rgba(99, 102, 241, 0.15)' : 'rgba(255,255,255,0.02)'}; border: 1px solid ${isSelected ? 'var(--primary)' : 'var(--border-color)'}; color: ${isSelected ? '#fff' : 'var(--text-secondary)'}; padding: 16px 20px; border-radius: 8px; text-align: left; cursor: pointer; font-size: 0.95rem; display: flex; align-items: center; gap: 12px; transition: all 0.15s ease;"
              >
                <span style="display: inline-flex; width: 28px; height: 28px; border-radius: 50%; background: ${isSelected ? 'var(--primary)' : 'rgba(255,255,255,0.05)'}; color: ${isSelected ? '#fff' : 'var(--text-secondary)'}; align-items: center; justify-content: center; font-weight: 700;">${opt}</span>
                <span>${optText}</span>
              </button>
            `;
          }).join('')}
        </div>

        <div style="display: flex; justify-content: space-between;">
          <button
            id="prev-q-btn"
            class="btn btn-outline"
            style="opacity: ${currentIdx === 0 ? 0.5 : 1};"
            ${currentIdx === 0 ? 'disabled' : ''}
          >
            Previous
          </button>
          ${currentIdx === questions.length - 1 ? `
            <button id="submit-quiz-btn" class="btn btn-secondary" ${submitting ? 'disabled' : ''}>
              ${submitting ? 'Submitting...' : 'Submit Assessment'}
            </button>
          ` : `
            <button id="next-q-btn" class="btn btn-primary">
              Next
            </button>
          `}
        </div>
      </div>
    `;

    document.querySelectorAll('.option-btn').forEach(btn => {
      btn.addEventListener('click', () => {
        answers[currentQ.id] = btn.dataset.option;
        renderQuizView();
      });
    });

    const prevBtn = document.getElementById('prev-q-btn');
    if (prevBtn) {
      prevBtn.addEventListener('click', () => {
        if (currentIdx > 0) {
          currentIdx--;
          renderQuizView();
        }
      });
    }

    const nextBtn = document.getElementById('next-q-btn');
    if (nextBtn) {
      nextBtn.addEventListener('click', () => {
        if (currentIdx < questions.length - 1) {
          currentIdx++;
          renderQuizView();
        }
      });
    }

    const submitBtn = document.getElementById('submit-quiz-btn');
    if (submitBtn) {
      submitBtn.addEventListener('click', async () => {
        submitting = true;
        renderQuizView();

        try {
          result = await apiFetch(`/quizzes/${quizId}/attempt`, {
            method: 'POST',
            body: { answers }
          });
          attempts = await apiFetch(`/quizzes/${quizId}/attempts`);
          activeStep = 'RESULT';
        } catch (err) {
          console.error(err);
          alert('Failed to submit quiz attempt.');
        } finally {
          submitting = false;
          renderQuizView();
        }
      });
    }

  } else if (activeStep === 'RESULT' && result) {
    container.innerHTML = `
      <div class="glass-card" style="padding: 40px;">
        <div style="text-align: center; margin-bottom: 40px;">
          <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="var(--secondary)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin: 0 auto 16px;">
            <circle cx="12" cy="8" r="7"></circle>
            <polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"></polyline>
          </svg>
          <h1 style="font-size: 2.2rem;">Assessment Completed</h1>
          <p style="color: var(--text-secondary); margin-top: 8px;">Your responses have been processed.</p>
          
          <div style="display: inline-flex; background: rgba(255,255,255,0.03); border: 1px solid var(--border-color); padding: 24px 40px; border-radius: 16px; margin-top: 24px; flex-direction: column; gap: 8px;">
            <span style="font-size: 3rem; font-weight: 800; color: var(--secondary);">
              ${result.score} / ${result.totalQuestions}
            </span>
            <span style="font-size: 0.9rem; color: var(--text-secondary);">
              Percentage: ${Math.round((result.score * 100) / result.totalQuestions)}%
            </span>
          </div>
        </div>

        <h3 style="font-size: 1.25rem; margin-bottom: 20px; border-bottom: 1px solid var(--border-color); padding-bottom: 12px;">Review Questions</h3>
        
        <div style="display: flex; flex-direction: column; gap: 32px; margin-bottom: 40px;">
          ${questions.map((q, idx) => {
            const selectedOpt = answers[q.id];
            const correctOpt = q.correctAnswer;
            const isCorrect = selectedOpt === correctOpt;
            
            return `
              <div>
                <div style="display: flex; gap: 8px; align-items: flex-start; margin-bottom: 12px;">
                  ${isCorrect ? `
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--secondary)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="flex-shrink: 0; margin-top: 2px;">
                      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                      <polyline points="22 4 12 14.01 9 11.01"></polyline>
                    </svg>
                  ` : `
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--danger)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="flex-shrink: 0; margin-top: 2px;">
                      <circle cx="12" cy="12" r="10"></circle>
                      <line x1="15" y1="9" x2="9" y2="15"></line>
                      <line x1="9" y1="9" x2="15" y2="15"></line>
                    </svg>
                  `}
                  <h4 style="font-size: 1.05rem; line-height: 1.4; color: #fff;">
                    ${idx + 1}. ${q.question}
                  </h4>
                </div>

                <div style="display: flex; flex-direction: column; gap: 8px; padding-left: 32px;">
                  ${['A', 'B', 'C', 'D'].map(opt => `
                    <div style="padding: 10px 14px; border-radius: 6px; font-size: 0.9rem; background: ${opt === correctOpt ? 'rgba(16, 185, 129, 0.1)' : (opt === selectedOpt ? 'rgba(239, 68, 68, 0.1)' : 'rgba(255,255,255,0.01)')}; border: 1px solid ${opt === correctOpt ? 'rgba(16, 185, 129, 0.2)' : (opt === selectedOpt ? 'rgba(239, 68, 68, 0.2)' : 'var(--border-color)')}; color: ${opt === correctOpt ? 'var(--secondary)' : (opt === selectedOpt ? 'var(--danger)' : 'var(--text-secondary)')};">
                      ${opt}. ${q[`option${opt}`]}
                    </div>
                  `).join('')}
                </div>

                <!-- AI Explanation Box -->
                <div style="margin-top: 16px; margin-left: 32px; background: rgba(99, 102, 241, 0.05); border: 1px solid rgba(99, 102, 241, 0.15); padding: 16px; border-radius: 8px; font-size: 0.85rem; display: flex; gap: 8px; align-items: flex-start;">
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="flex-shrink: 0; margin-top: 2px;">
                    <circle cx="12" cy="12" r="10"></circle>
                    <line x1="12" y1="8" x2="12" y2="12"></line>
                    <line x1="12" y1="16" x2="12.01" y2="16"></line>
                  </svg>
                  <div>
                    <strong style="color: #fff; display: block; margin-bottom: 4px;">AI Explanation:</strong>
                    <span style="color: var(--text-secondary);">${q.explanation}</span>
                  </div>
                </div>
              </div>
            `;
          }).join('')}
        </div>

        <div style="display: flex; gap: 16px;">
          <button id="retake-quiz-btn" class="btn btn-outline" style="flex: 1;">
            Retake Assessment
          </button>
          <button id="back-course-btn" class="btn btn-primary" style="flex: 1;">
            Back to Course
          </button>
        </div>
      </div>
    `;

    const retakeBtn = document.getElementById('retake-quiz-btn');
    if (retakeBtn) {
      retakeBtn.addEventListener('click', () => {
        answers = {};
        currentIdx = 0;
        activeStep = 'ATTEMPT';
        renderQuizView();
      });
    }

    const backBtn = document.getElementById('back-course-btn');
    if (backBtn) {
      backBtn.addEventListener('click', () => {
        window.history.back();
      });
    }
  }
}
